# Common setting
baseURL = "http://minyez.space/"

defaultContentLanguage = "en"

title = "minyez.space"
theme = "yinyang"

footnoteReturnLinkContents = "↩"

# use content directories for content translation
[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    weight = 1
